### ISSUE TITLE
difference with paper

### ISSUE THREAD

**Issue by nicetomeetu21** [LongguangWang/SMSR#12]
https://github.com/LongguangWang/SMSR/blob/af9b04ceb5e6820f5df5e372f58f66bb8f85d024/model/smsr.py#L253

I suggest that the subscript of ch_mask may be [:,:,i-1:i,:1]

**Comment by nicetomeetu21** [comment]
Supplement: Fig. 5 in the paper shows that the feature should multiply with the channel mask of the last layer before convolutions. But in the code, the feature multiply with the channel mask of the current layer. pls check the code.

**Comment by LongguangWang** [comment]
Hi @nicetomeetu21, thanks for reporting this issue and we have fixed it.
