### ISSUE TITLE
Sparse Convolution

### ISSUE THREAD

**Issue by HaihuaQiu** [LongguangWang/SMSR#3]
Hello， can you introduce Sparse Convolution details?

**Comment by HaihuaQiu** [comment]
I can not undestand 'Implementation of Sparse Convolution' that you write in github...
Thank you

**Comment by LongguangWang** [comment]
Hi @HaihuaQiu, thanks for your interest in our work.
The key idea of our sparse convolution implementation is to divide the convolution into 4 branches (i.e., [dense->dense](https://github.com/LongguangWang/SMSR/blob/056c034c4c98172d6b7b504b5b33a9efff07d3dc/model/smsr.py#L183), [dense->sparse](https://github.com/LongguangWang/SMSR/blob/056c034c4c98172d6b7b504b5b33a9efff07d3dc/model/smsr.py#L193), [sparse->dense & sparse->sparse](https://github.com/LongguangWang/SMSR/blob/056c034c4c98172d6b7b504b5b33a9efff07d3dc/model/smsr.py#L199) ). Maybe you can make the question more specific that I can better help you to understand our code.
